openapi: 3.0.0
info:
  title: Discord Clone API
  version: '1.0'
  description: Backend for Discord Clone App
servers:
  - url: 'http://localhost:3000'
    description: Local
tags:
  - name: user
    description: Endpoint for user
paths:
  /v1/auth/register:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 142
                    name: norminet
                    email: norminet@42.fr
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
        '':
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
            examples:
              Create User Norminet:
                value:
                  name: norminet
                  email: norminet@42.fr
                  password: P@ssw0rd
        description: Post the necessary fields for the API to create a new user.
      description: 新たなアカウントの登録。
      tags:
        - auth
      security: []
    parameters: []
  /v1/auth/login:
    parameters: []
    post:
      summary: Login
      operationId: post-auth-login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 142
                    name: nop
                    email: nop@42tokyo.jp
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
      description: 既存アカウントにログインするために使う。これでトークンを取得する。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - name
                - password
            examples:
              example:
                value:
                  name: norminet
                  password: P@ssw0rd
        description: ''
      tags:
        - auth
  /v1/auth/logout:
    post:
      summary: Logout
      operationId: post-auth-logout
      responses:
        '200':
          description: OK
      tags:
        - auth
      description: アカウントからログアウトする。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
  '/v1/users/{id}':
    parameters:
      - $ref: '#/components/parameters/user-id'
    get:
      summary: Get User Info by User ID
      tags:
        - user
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 142
                    name: nop
                    email: nop@42tokyo.jp
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      security: []
    put:
      summary: Update User Information
      tags:
        - user
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: 142
                    name: nop
                    email: nop@42tokyo.jp
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            examples:
              example-1:
                value:
                  name: nop
                  email: nop@example.com
                  password: pa$$word
        description: Patch user properties to update.
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
  /v1/me:
    parameters: []
    get:
      summary: Get Own Account Data
      tags:
        - user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  me:
                    $ref: '#/components/schemas/User'
                  servers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Server'
                  private_messages:
                    type: array
                    items:
                      $ref: '#/components/schemas/PrivateMessage'
              examples:
                ネストされた全モデル:
                  value:
                    me:
                      id: 142
                      name: nop
                      email: nop@42tokyo.jp
                    servers:
                      - id: 0
                        name: string
                        channels:
                          - id: 0
                            name: string
                            messages:
                              - id: 0
                                from:
                                  id: 142
                                  name: nop
                                  email: nop@42tokyo.jp
                                to:
                                  id: 142
                                  name: nop
                                  email: nop@42tokyo.jp
                                content: string
                                sended_at: '2019-08-24T14:15:22Z'
                    private_messages:
                      - id: 0
                        destination:
                          id: 142
                          name: nop
                          email: nop@42tokyo.jp
                        messages:
                          - id: 0
                            from:
                              id: 142
                              name: nop
                              email: nop@42tokyo.jp
                            to:
                              id: 142
                              name: nop
                              email: nop@42tokyo.jp
                            content: string
                            sended_at: '2019-08-24T14:15:22Z'
                サーバーとDMの相手一覧だけ:
                  value:
                    me:
                      id: 42
                      name: nop
                      email: nop@42tokyo.jp
                    servers:
                      - id: 1
                        name: 42Tokyo
                      - id: 2
                        name: times
                    private_messages:
                      - id: 1
                        destination:
                          id: 21
                          name: bunjiro
                          email: bunjiro@42tokyo.jp
      operationId: get-users-userId-data
      description: |-
        DM・サーバー毎のメッセージを含む全てのデータを取得する。
        情報として多すぎるように思えるから、サーバーのIDと名前だけとって返すのがいいかも。
      parameters:
        - schema:
            type: string
          in: header
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
          name: Authorization
  /v1/servers:
    get:
      summary: Get Server Information
      tags:
        - server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Server'
              examples:
                ネストされた全モデル:
                  value:
                    - id: 0
                      name: string
                      channels:
                        - id: 0
                          name: string
                          messages:
                            - id: 0
                              from:
                                id: 142
                                name: nop
                                email: nop@42tokyo.jp
                              to:
                                id: 142
                                name: nop
                                email: nop@42tokyo.jp
                              content: string
                              sended_at: '2019-08-24T14:15:22Z'
                サーバー一覧のみ:
                  value:
                    - id: 1
                      name: 42tokyo
                    - id: 2
                      name: times
                チャンネルまで:
                  value:
                    - id: 1
                      name: 42tokyo
                      channels:
                        - id: 1
                          name: general
                        - id: 2
                          name: random
                    - id: 2
                      name: times
                      channels:
                        - id: 1
                          name: nop
                        - id: 2
                          name: bunjiro
      operationId: get-servers
      description: サーバー一覧を取得する。チャネルの名前とIDだけで留めておくのがいいかも。
    post:
      summary: Create New Server
      operationId: post-servers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
              examples:
                example-1:
                  value:
                    id: 1
                    name: 42tokyo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Server'
            examples:
              example-1:
                value:
                  name: 42tokyo
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      tags:
        - server
      description: 新たにサーバーを作るためのエンドポイント。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
  '/v1/servers/{id}':
    parameters:
      - $ref: '#/components/parameters/server-id'
    get:
      summary: Get Specified Server Information
      tags:
        - server
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
              examples:
                ネストされた全モデル:
                  value:
                    id: 1
                    name: 42tokyo
                    channels:
                      - id: 1
                        name: general
                        messages:
                          - id: 0
                            from:
                              id: 142
                              name: nop
                              email: nop@42tokyo.jp
                            content: hello world
                            sended_at: '2019-08-24T14:15:22Z'
                チャンネル名まで:
                  value:
                    id: 0
                    name: 42tokyo
                    channels:
                      - id: 1
                        name: general
                      - id: 2
                        name: random
      operationId: get-servers-id
      description: IDで指定したサーバーの中身を返す。ここではサーバー内の全チャンネル一覧を合わせて返すのが良さそう。
    put:
      summary: Update Server Meta Data
      operationId: put-servers-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
              examples:
                example-1:
                  value:
                    id: 1
                    name: 42tokyo
      tags:
        - server
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Server'
            examples:
              example-1:
                value:
                  name: 42tokyo
      description: サーバーの名前・所有者の変更。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
    delete:
      summary: ''
      operationId: delete-servers-id
      responses:
        '200':
          description: OK
      tags:
        - server
      description: 指定したサーバーを削除する。
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
  /v1/channels:
    get:
      summary: Get Channels List
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
              examples:
                全モデル:
                  value:
                    - id: 1
                      name: general
                      messages:
                        - id: 1
                          from:
                            id: 142
                            name: nop
                            email: nop@42tokyo.jp
                          content: hello world
                          sended_at: '2019-08-24T14:15:22Z'
                チャンネル名まで:
                  value:
                    - id: 1
                      name: general
                    - id: 2
                      name: random
      operationId: get-Channels
      tags:
        - channel
      description: モデルを入れ子にしているから、全チャネルのメッセージ全てを取得してしまいそう。モデルで各要素の上限を設定して、親モデルを取得する時は上限までで止めるといいかも。
    post:
      summary: Create Channel
      operationId: post-Channels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
              examples:
                example-1:
                  value:
                    id: '1'
                    name: random
      description: チャンネルを新たに作成する。
      tags:
        - channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            examples:
              example-1:
                value:
                  name: random
    parameters: []
  '/v1/channels/{id}':
    parameters:
      - $ref: '#/components/parameters/channel-id'
    get:
      summary: Get Specifed Channel Information
      tags:
        - channel
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
              examples:
                example-1:
                  value:
                    id: 1
                    name: general
                    messages:
                      - id: 1
                        from:
                          id: 142
                          name: nop
                          email: nop@42tokyo.jp
                        content: hello world
                        sended_at: '2019-08-24T14:15:22Z'
                      - id: 2
                        from:
                          id: 142
                          name: nop
                          email: nop@42tokyo.jp
                        content: hello 42tokyo
                        sended_at: '2019-08-25T14:15:22Z'
      operationId: get-Channels-id
      description: |-
        指定したチャンネルの情報を全て返す。
        メッセージは直近20件くらいを返すとポータブルで良さそう。
    put:
      summary: ''
      operationId: put-Channels-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Channel'
              examples:
                example-1:
                  value:
                    id: 1
                    name: random
      tags:
        - channel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
            examples:
              example-1:
                value:
                  name: random
    delete:
      summary: ''
      operationId: delete-Channels-id
      responses:
        '200':
          description: OK
      tags:
        - channel
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2Vybm...
  '/v1/channels/{id}/messages':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get Messages in Specified Channel
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
              examples:
                example-1:
                  value:
                    - id: 1
                      from:
                        id: 142
                        name: nop
                        email: nop@42tokyo.jp
                      content: hello
                      sended_at: '2019-08-24T14:15:22Z'
      operationId: get-channels-id-messages
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
        - schema:
            type: string
          in: query
          name: order_by
      description: |-
        チャンネル内のメッセージの一覧を取得。上限100くらいにしておく（デフォルト20）。
        クエリパラメータでレンジを指定する。
        並び順もクエリで指定できると良いかも。
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          name: nop
          email: nop@42tokyo.jp
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
          description: Username
        email:
          type: string
          format: email
      required:
        - id
        - name
        - email
      x-examples:
        norminet:
          id: 142
          name: norminet
          email: norminet@42.fr
    Server:
      title: Server
      type: object
      x-examples:
        example-1:
          id: 26
          name: 42 Tokyo
          channels:
            - id: 1
              name: general
              messages:
                - id: 1
                  sender: norminet
                  content: Hello 42Tokyo!
                  sended_at: '2019-08-24T14:15:22Z'
                - id: 3
                  sender: nop
                  content: Don't Panic.
                  sended_at: '2019-08-24T15:42:00Z'
            - id: 2
              name: random
              messages:
                - id: 2
                  sender: arthur
                  content: So this is it.
                  sended_at: '2019-08-24T15:41:22Z'
                - id: 4
                  sender: ford
                  content: We are going to die.
                  sended_at: '2019-08-24T15:42:22Z'
                - id: 5
                  sender: arthur
                  content: Yes.
                  sended_at: '2019-08-24T15:43:22Z'
                - id: 6
                  sender: arthur
                  content: Except... no! Wait a minute!
                  sended_at: '2019-08-24T15:44:22Z'
                - id: 7
                  sender: arthur
                  content: What's this switch?
                  sended_at: '2019-08-24T15:45:22Z'
                - id: 8
                  sender: arthur
                  content: What? Where?
                  sended_at: '2019-08-24T15:46:22Z'
                - id: 9
                  sender: ford
                  content: 'No, I was only fooling.'
                  sended_at: '2019-08-24T15:47:22Z'
                - id: 10
                  sender: ford
                  content: We are going to die after all.
                  sended_at: '2019-08-24T15:48:22Z'
      properties:
        id:
          type: integer
        name:
          type: string
        channels:
          type: array
          items:
            $ref: '#/components/schemas/Channel'
      required:
        - id
        - name
    Channel:
      title: Channel
      type: object
      x-examples:
        example-1:
          id: 1
          name: general
          messages:
            - id: 1
              sender: norminet
              content: Hello 42Tokyo!
              sended_at: '2019-08-24T14:15:22Z'
            - id: 3
              sender: nop
              content: Don't Panic.
              sended_at: '2019-08-24T15:15:22Z'
      description: ''
      properties:
        id:
          type: integer
        name:
          type: string
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      required:
        - id
        - name
    Message:
      title: Message
      type: object
      x-examples:
        example-1:
          id: 42
          sender: norminet
          content: hello 42Tokyo
          sended_at: '2020-06-22T00:42:42Z'
      properties:
        id:
          type: integer
        from:
          $ref: '#/components/schemas/User'
        to:
          $ref: '#/components/schemas/User'
        content:
          type: string
        sended_at:
          type: string
          format: date-time
      required:
        - id
        - from
        - content
        - sended_at
    PrivateMessage:
      title: Private Message
      type: object
      x-examples:
        example-1:
          id: 0
          destination:
            id: 142
            name: nop
            email: nop@42tokyo.jp
          messages:
            - id: 0
              from:
                id: 142
                name: nop
                email: nop@42tokyo.jp
              to:
                id: 142
                name: nop
                email: nop@42tokyo.jp
              content: string
              sended_at: '2019-08-24T14:15:22Z'
      description: ''
      properties:
        id:
          type: integer
        destination:
          $ref: '#/components/schemas/User'
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      required:
        - id
        - destination
  securitySchemes:
    OAuth2:
      type: oauth2
      description: User login
      flows:
        password:
          scopes: {}
  parameters:
    user-id:
      name: user id
      in: path
      required: true
      schema:
        type: integer
      description: user id
    server-id:
      name: server-id
      in: path
      required: true
      schema:
        type: string
      description: server id
    channel-id:
      name: channel-id
      in: path
      required: true
      schema:
        type: string
      description: channel id
  examples: {}
security:
  - OAuth2: []
